name: Run Cypress Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cy:run   # roda todos os testes (web + api)

      - name: Save Allure Results as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  generate-report:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Allure Results Artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          curl -o allure.tar.gz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -zxvf allure.tar.gz -C /opt/
          sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          commit_message: 'Deploy Allure Report'
          keep_files: true
